version: 2

models:
  - name: county_fact_driving_test_statistics
    description: >
      Fact table aggregating driving test data at the county level, including population, total tests conducted, and tests per capita.
    columns:
      - name: county_name
        description: Name of the county.
        tests:
          - not_null
      - name: test_year
        description: Year in which driving tests were conducted.
        tests:
          - not_null
      - name: population
        description: Population of the county in the given year.
        tests:
          - not_null
      - name: population_year
        description: Year the population data corresponds to.
        tests:
          - not_null
      - name: tests_conducted
        description: Total number of driving tests conducted in the county during the year.
        tests:
          - not_null
      - name: tests_per_capita
        description: Ratio of tests conducted to population in the county.
        tests:
          - not_null
    tests:
      - unique:
          column_name: "(county_name || '-' || test_year)"

  - name: test_centre_fact_driving_stats
    description: >
      Fact table aggregating driving test statistics at the test centre level, including pass rates and test volumes.
    columns:
      - name: test_centre_name
        description: Name of the driving test centre.
        tests:
          - not_null
      - name: county
        description: County where the test centre is located.
        tests:
          - not_null
      - name: year
        description: Year the data relates to.
        tests:
          - not_null
      - name: tests_conducted
        description: Total number of tests conducted at the centre in the given year.
        tests:
          - not_null
      - name: tests_passed
        description: Number of tests passed at the centre.
        tests:
          - not_null
      - name: pass_rate
        description: Pass rate calculated as passed tests divided by total conducted.
        tests:
          - not_null
    tests:
      - unique:
          column_name: "(test_centre_name || '-' || year)"
